Import('env', 'plugins')

# Basic library of smooth and rough materials
plugins += env.SharedLibrary('diffuse', ['diffuse.cpp'])
plugins += env.SharedLibrary('dielectric', ['dielectric.cpp'])
plugins += env.SharedLibrary('conductor', ['conductor.cpp'])
plugins += env.SharedLibrary('plastic', ['plastic.cpp'])
plugins += env.SharedLibrary('roughdiffuse', ['roughdiffuse.cpp'])
plugins += env.SharedLibrary('roughdielectric', ['roughdielectric.cpp'])
plugins += env.SharedLibrary('roughconductor', ['roughconductor.cpp'])
plugins += env.SharedLibrary('roughplastic', ['roughplastic.cpp'])

plugins += env.SharedLibrary('aniso_roughdiffuse', ['aniso_roughdiffuse.cpp'])
plugins += env.SharedLibrary('aniso_roughdiffuse_simple', ['aniso_roughdiffuse_simple.cpp'])
plugins += env.SharedLibrary('multilobe_bsdf', ['multilobe_bsdf.cpp'])
plugins += env.SharedLibrary('tabulated_bsdf', ['tabulated_bsdf.cpp'])

plugins += env.SharedLibrary('roughdiffuse_multi', ['roughdiffuse_multi.cpp'])
plugins += env.SharedLibrary('roughbsdf_multi', ['roughbsdf_multi.cpp'])
plugins += env.SharedLibrary('sh_scaled_bsdf', ['sh_scaled_bsdf.cpp'])
plugins += env.SharedLibrary('tabulated_scaled_bsdf', ['tabulated_scaled_bsdf.cpp'])
plugins += env.SharedLibrary('heightmap_bsdf', ['heightmap_bsdf.cpp'])

# Materials that act as modifiers
plugins += env.SharedLibrary('twosided', ['twosided.cpp'])
plugins += env.SharedLibrary('mask', ['mask.cpp'])
plugins += env.SharedLibrary('mixturebsdf', ['mixturebsdf.cpp'])
plugins += env.SharedLibrary('blendbsdf', ['blendbsdf.cpp'])
plugins += env.SharedLibrary('coating', ['coating.cpp'])
plugins += env.SharedLibrary('roughcoating', ['roughcoating.cpp'])
plugins += env.SharedLibrary('bumpmap', ['bumpmap.cpp'])
plugins += env.SharedLibrary('normalmap', ['normalmap.cpp'])

# Other materials
plugins += env.SharedLibrary('ward', ['ward.cpp'])
plugins += env.SharedLibrary('phong', ['phong.cpp'])
plugins += env.SharedLibrary('difftrans', ['difftrans.cpp'])
plugins += env.SharedLibrary('hk', ['hk.cpp'])
plugins += env.SharedLibrary('null', ['null.cpp'])
plugins += env.SharedLibrary('thindielectric', ['thindielectric.cpp'])

# The Irawan-Marschner plugin uses a Boost::Spirit parser, which makes it
# pretty heavy stuff to compile. Go easy on the compiler flags:
irawanEnv = env.Clone()
irawanEnv.RelaxCompilerSettings()
plugins += irawanEnv.SharedLibrary('irawan', ['irawan.cpp'])

Export('plugins')
