Import('env', 'plugins')

plugins += env.SharedLibrary('instancedvol', ['instancedvol.cpp'])
plugins += env.SharedLibrary('shellvolume2', ['shellmap2.cpp'])
plugins += env.SharedLibrary('tiledvol', ['tiledvol.cpp'])
plugins += env.SharedLibrary('gridvolumeSimple', ['gridvol_simple.cpp'])

plugins += env.SharedLibrary('constvolume', ['constvolume.cpp'])
plugins += env.SharedLibrary('gridvolume', ['gridvolume.cpp'])
plugins += env.SharedLibrary('hgridvolume', ['hgridvolume.cpp'])
plugins += env.SharedLibrary('volcache', ['volcache.cpp'])

Export('plugins')
